spring:
  jpa:
    database: H2
    show-sql: false
    hibernate:
      ddlAuto: none
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    platform: h2
    driverClassName: org.h2.Driver
  flyway:
    locations: classpath:/db/migration
